name: Lint

on:
  push:
    branches: [ main, master, Preview, beta ]
  pull_request:
    branches: [ main, master, Preview, beta ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install ESLint plugin for Jest
        run: npm install --save-dev eslint-plugin-jest
        continue-on-error: true
      
      - name: Run ESLint
        run: npx eslint src --ext .ts,.tsx
        continue-on-error: true
      
      - name: Run Prettier check
        run: npx prettier --check "src/**/*.{ts,tsx}"
        continue-on-error: true