name: Create Release

on:
  push:
    branches:
      - master   # Stable releases
      - beta     # Beta releases
      - preview  # Preview releases
    paths:
      - 'package.json' # Only trigger when package.json changes (likely version updates)

# Add necessary permissions
permissions:
  contents: write # Permission to create releases
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Need full history for versioning

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Get version and determine release type
        id: package_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
          # Determine release type based on branch
          BRANCH=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH" == "preview" ]]; then
            echo "TYPE=preview" >> $GITHUB_OUTPUT
            echo "This is a preview release from preview branch"
          elif [[ "$BRANCH" == "beta" ]]; then
            echo "TYPE=beta" >> $GITHUB_OUTPUT
            echo "This is a beta release from beta branch"
          elif [[ "$BRANCH" == "master" ]]; then
            echo "TYPE=stable" >> $GITHUB_OUTPUT
            echo "This is a stable release from master branch"
          else
            echo "TYPE=development" >> $GITHUB_OUTPUT
            echo "This is a development build from $BRANCH branch"
          fi

      - name: Create zip archive
        run: |
          RELEASE_TYPE=${{ steps.package_version.outputs.TYPE }}
          VERSION=${{ steps.package_version.outputs.VERSION }}
          ZIP_NAME="samskrit-language-v${VERSION}-${RELEASE_TYPE}"
          zip -r "${ZIP_NAME}.zip" dist LICENSE README.md package.json
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
          echo "Created archive for $RELEASE_TYPE release v$VERSION"
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.package_version.outputs.VERSION }}-${{ steps.package_version.outputs.TYPE }}
          name: Sanskrit Language v${{ steps.package_version.outputs.VERSION }} (${{ steps.package_version.outputs.TYPE }})
          files: |
            ${{ env.ZIP_NAME }}.zip
          draft: false
          prerelease: ${{ steps.package_version.outputs.TYPE != 'stable' }}
          generate_release_notes: true
          body: |
            ## Sanskrit Language v${{ steps.package_version.outputs.VERSION }} (${{ steps.package_version.outputs.TYPE }} release)
            
            Built from the ${{ github.ref_name }} branch.
            
            ### Installation
            Download the zip file and extract it to your preferred location. 
            
            ### Getting Started
            Refer to the documentation in the README.md file for details on how to use the Sanskrit Language. 